### ISSUE TITLE
Restore - username update fails if admin is the only user found

### ISSUE THREAD

**Issue by pehruby** [cisco-open/sdwan-lab-deployment-tool#32]
## Description

pehruby@CZCW00095:/mnt/d/pehruby/Documents/Programovani/csdwan$ csdwan restore
SD-WAN Manager password: 
Updating lab parameters...
Traceback (most recent call last):
  File "/home/pehruby/.local/bin/csdwan", line 8, in <module>
    sys.exit(main())
  File "/home/pehruby/.local/lib/python3.10/site-packages/catalyst_sdwan_lab/__main__.py", line 576, in main
    restore.main(
  File "/home/pehruby/.local/lib/python3.10/site-packages/catalyst_sdwan_lab/tasks/restore.py", line 149, in main
    existing_manager_users[0], manager_user
IndexError: list index out of range

## Expected Behavior

no error

## Actual Behavior

existing_manager_users list is emty

## Affected Version

2.0.13

## Steps to Reproduce

1. csdwan restore

## Checklist

- [x] I have read the [contributing guidelines](/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

**Comment by tzarski0** [comment]
Fixed in 2.0.14.
